---
# =========================================
# Cisco IOS-XR Router RTR STIG - Routing
# 30 rules
# =========================================

# -----------------------------------------
# CISC-RT-000050 - MEDIUM
# -----------------------------------------

- name: "CISC-RT-000050 | The Cisco router must be configured to enable routing protocol authentication using FIPS 198-1 algorithms with keys not exceeding 180 days of lifetime."
  cisco.iosxr.iosxr_config:
    lines:
      - "key chain <KEY-CHAIN-NAME>"
      - "key <KEY-ID>"
      - "key <KEY-ID> SendID <ID> ReceiveID <ID>"
      - "router bgp <ASN>"
      - "key chain OSPF_KEY_CHAIN"
  notify: Save running configuration
  tags:
    - CISC-RT-000050
    - cat2
    - routing

# -----------------------------------------
# CISC-RT-000290 - HIGH
# -----------------------------------------

- name: "CISC-RT-000290 | The Cisco perimeter router must be configured to not be a Border Gateway Protocol (BGP) peer to an alternate gateway service provider."
  cisco.ios.ios_config:
    lines:
      - "ip route 0.0.0.0 0.0.0.0 {{ peer_address }}"
  notify: Save running configuration
  tags:
    - CISC-RT-000290
    - cat1
    - routing

# -----------------------------------------
# CISC-RT-000300 - LOW
# -----------------------------------------

- name: "CISC-RT-000300 | MANUAL CHECK - The Cisco perimeter router must be configured to not redistribute static routes to an alternate gateway service provider into BGP or an IGP peering wi"
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure BGP as required."
  tags:
    - CISC-RT-000300
    - cat3
    - routing

# -----------------------------------------
# CISC-RT-000430 - MEDIUM
# -----------------------------------------

- name: "CISC-RT-000430 | MANUAL CHECK - The Cisco out-of-band management (OOBM) gateway router must be configured to not redistribute routes between the management network routing domain and"
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure the device CLI as required."
  tags:
    - CISC-RT-000430
    - cat2
    - routing

# -----------------------------------------
# CISC-RT-000490 - MEDIUM
# -----------------------------------------

- name: "CISC-RT-000490 | MANUAL CHECK - The Cisco BGP router must be configured to reject inbound route advertisements for any Bogon prefixes."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure BGP as required."
  tags:
    - CISC-RT-000490
    - cat2
    - routing

# -----------------------------------------
# CISC-RT-000500 - MEDIUM
# -----------------------------------------

- name: "CISC-RT-000500 | MANUAL CHECK - The Cisco BGP router must be configured to reject inbound route advertisements for any prefixes belonging to the local autonomous system (AS)."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure BGP as required."
  tags:
    - CISC-RT-000500
    - cat2
    - routing

# -----------------------------------------
# CISC-RT-000510 - MEDIUM
# -----------------------------------------

- name: "CISC-RT-000510 | MANUAL CHECK - The Cisco BGP router must be configured to reject inbound route advertisements from a customer edge (CE) router for prefixes that are not allocated to"
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure BGP as required."
  tags:
    - CISC-RT-000510
    - cat2
    - routing

# -----------------------------------------
# CISC-RT-000520 - MEDIUM
# -----------------------------------------

- name: "CISC-RT-000520 | MANUAL CHECK - The Cisco BGP router must be configured to reject outbound route advertisements for any prefixes that do not belong to any customers or the local auto"
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure BGP as required."
  tags:
    - CISC-RT-000520
    - cat2
    - routing

# -----------------------------------------
# CISC-RT-000530 - MEDIUM
# -----------------------------------------

- name: "CISC-RT-000530 | MANUAL CHECK - The Cisco BGP router must be configured to reject outbound route advertisements for any prefixes belonging to the IP core."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure BGP as required."
  tags:
    - CISC-RT-000530
    - cat2
    - routing

# -----------------------------------------
# CISC-RT-000540 - LOW
# -----------------------------------------

- name: "CISC-RT-000540 | MANUAL CHECK - The Cisco BGP router must be configured to reject route advertisements from BGP peers that do not list their autonomous system (AS) number as the firs"
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure BGP as required."
  tags:
    - CISC-RT-000540
    - cat3
    - routing

# -----------------------------------------
# CISC-RT-000550 - LOW
# -----------------------------------------

- name: "CISC-RT-000550 | MANUAL CHECK - The Cisco BGP router must be configured to reject route advertisements from CE routers with an originating AS in the AS_PATH attribute that does not b"
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure BGP as required."
  tags:
    - CISC-RT-000550
    - cat3
    - routing

# -----------------------------------------
# CISC-RT-000560 - MEDIUM
# -----------------------------------------

- name: "CISC-RT-000560 | MANUAL CHECK - The Cisco BGP router must be configured to use the maximum prefixes feature to protect against route table flooding and prefix de-aggregation attacks."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure BGP as required."
  tags:
    - CISC-RT-000560
    - cat2
    - routing

# -----------------------------------------
# CISC-RT-000570 - LOW
# -----------------------------------------

- name: "CISC-RT-000570 | MANUAL CHECK - The Cisco BGP router must be configured to limit the prefix size on any inbound route advertisement to /24 or the least significant prefixes issued to"
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure BGP as required."
  tags:
    - CISC-RT-000570
    - cat3
    - routing

# -----------------------------------------
# CISC-RT-000580 - LOW
# -----------------------------------------

- name: "CISC-RT-000580 | MANUAL CHECK - The Cisco BGP router must be configured to use its loopback address as the source address for iBGP peering sessions."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure BGP as required."
  tags:
    - CISC-RT-000580
    - cat3
    - routing

# -----------------------------------------
# CISC-RT-000590 - LOW
# -----------------------------------------

- name: "CISC-RT-000590 | MANUAL CHECK - The Cisco MPLS router must be configured to use its loopback address as the source address for LDP peering sessions."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure the device CLI as required."
  tags:
    - CISC-RT-000590
    - cat3
    - routing

# -----------------------------------------
# CISC-RT-000600 - LOW
# -----------------------------------------

- name: "CISC-RT-000600 | MANUAL CHECK - The Cisco MPLS router must be configured to synchronize IGP and LDP to minimize packet loss when an IGP adjacency is established prior to LDP peers co"
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure the device CLI as required."
  tags:
    - CISC-RT-000600
    - cat3
    - routing

# -----------------------------------------
# CISC-RT-000610 - LOW
# -----------------------------------------

- name: "CISC-RT-000610 | MANUAL CHECK - The MPLS router with RSVP-TE enabled must be configured with message pacing to adjust maximum burst and maximum number of RSVP messages to an output q"
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure the device CLI as required."
  tags:
    - CISC-RT-000610
    - cat3
    - routing

# -----------------------------------------
# CISC-RT-000620 - MEDIUM
# -----------------------------------------

- name: "CISC-RT-000620 | MANUAL CHECK - The Cisco MPLS router must be configured to have TTL Propagation disabled."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure the device CLI as required."
  tags:
    - CISC-RT-000620
    - cat2
    - routing

# -----------------------------------------
# CISC-RT-000630 - HIGH
# -----------------------------------------

- name: "CISC-RT-000630 | MANUAL CHECK - The Cisco PE router must be configured to have each Virtual Routing and Forwarding (VRF) instance bound to the appropriate physical or logical interfaces to maintain traffic separation between all ..."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Configure the PE router to have each VRF bound to the appropriate physical or logical interfaces to maintain traffic separation between all MPLS L3VPNs."
  tags:
    - CISC-RT-000630
    - cat1
    - routing

# -----------------------------------------
# CISC-RT-000640 - HIGH
# -----------------------------------------

- name: "CISC-RT-000640 | MANUAL CHECK - The Cisco PE router must be configured to have each Virtual Routing and Forwarding (VRF) instance with the appropriate Route Target (RT)."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure the device CLI as required."
  tags:
    - CISC-RT-000640
    - cat1
    - routing

# -----------------------------------------
# CISC-RT-000650 - MEDIUM
# -----------------------------------------

- name: "CISC-RT-000650 | MANUAL CHECK - The Cisco PE router must be configured to have each VRF with the appropriate Route Distinguisher (RD)."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure the device CLI as required."
  tags:
    - CISC-RT-000650
    - cat2
    - routing

# -----------------------------------------
# CISC-RT-000670 - HIGH
# -----------------------------------------

- name: "CISC-RT-000670 | MANUAL CHECK - The Cisco PE router providing MPLS Virtual Private Wire Service (VPWS) must be configured to have the appropriate pseudowire ID for each attachment ci"
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure the device CLI as required."
  tags:
    - CISC-RT-000670
    - cat1
    - routing

# -----------------------------------------
# CISC-RT-000790 - MEDIUM
# -----------------------------------------

- name: "CISC-RT-000790 | MANUAL CHECK - The Cisco multicast router must be configured to disable Protocol Independent Multicast (PIM) on all interfaces that are not required to support multi"
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure the device as required."
  tags:
    - CISC-RT-000790
    - cat2
    - routing

# -----------------------------------------
# CISC-RT-000940 - LOW
# -----------------------------------------

- name: "CISC-RT-000940 | MANUAL CHECK - The Cisco Multicast Source Discovery Protocol (MSDP) router must be configured to limit the amount of source-active messages it accepts on a per-peer"
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure the device CLI as required."
  tags:
    - CISC-RT-000940
    - cat3
    - routing

# -----------------------------------------
# CISC-RT-000350 - MEDIUM
# -----------------------------------------

- name: "CISC-RT-000350 | MANUAL CHECK - The Cisco perimeter router must be configured to block all packets with any IP options."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure the device CLI as required."
  tags:
    - CISC-RT-000350
    - cat2
    - routing

# -----------------------------------------
# CISC-RT-000470 - LOW
# -----------------------------------------

- name: "CISC-RT-000470 | MANUAL CHECK - The Cisco BGP router must be configured to enable the Generalized TTL Security Mechanism (GTSM)."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure BGP as required."
  tags:
    - CISC-RT-000470
    - cat3
    - routing

# -----------------------------------------
# CISC-RT-000480 - MEDIUM
# -----------------------------------------

- name: "CISC-RT-000480 | MANUAL CHECK - The Cisco BGP router must be configured to use a unique key for each autonomous system (AS) that it peers with."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure BGP as required."
  tags:
    - CISC-RT-000480
    - cat2
    - routing

# -----------------------------------------
# CISC-RT-000750 - MEDIUM
# -----------------------------------------

- name: "CISC-RT-000750 | MANUAL CHECK - The Cisco PE router must be configured to ignore or block all packets with any IP options."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure the device CLI as required."
  tags:
    - CISC-RT-000750
    - cat2
    - routing

# -----------------------------------------
# CISC-RT-000235 - MEDIUM
# -----------------------------------------

- name: "CISC-RT-000235 | MANUAL CHECK - The Cisco router must be configured to have Cisco Express Forwarding enabled."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure the device CLI as required."
  tags:
    - CISC-RT-000235
    - cat2
    - routing

# -----------------------------------------
# CISC-RT-000236 - LOW
# -----------------------------------------

- name: "CISC-RT-000236 | The Cisco router must be configured to advertise a hop limit of at least 32 in Router Advertisement messages for IPv6 stateless auto-configuration deployments."
  cisco.iosxr.iosxr_config:
    lines:
      - "ipv6 hop-limit 128"
  notify: Save running configuration
  tags:
    - CISC-RT-000236
    - cat3
    - routing

