---
# =========================================
# Cisco IOS Router RTR STIG - Authentication
# 3 rules
# =========================================

# -----------------------------------------
# CISC-RT-000230 - LOW
# -----------------------------------------

- name: "CISC-RT-000230 | The Cisco router must be configured to disable the auxiliary port unless it is connected to a secured modem providing encryption and authentication."
  cisco.ios.ios_config:
    lines:
      - "line aux 0"
      - "no exec"
      - "transport input none"
  notify: Save running configuration
  tags:
    - CISC-RT-000230
    - cat3
    - authentication

# -----------------------------------------
# CISC-RT-000660 - MEDIUM
# -----------------------------------------

- name: "CISC-RT-000660 | MANUAL CHECK - The Cisco PE router providing MPLS Layer 2 Virtual Private Network (L2VPN) services must be configured to authenticate targeted Label Distribution Pro"
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure the device CLI as required."
  tags:
    - CISC-RT-000660
    - cat2
    - authentication

# -----------------------------------------
# CISC-RT-000910 - MEDIUM
# -----------------------------------------

- name: "CISC-RT-000910 | The Cisco Multicast Source Discovery Protocol (MSDP) router must be configured to authenticate all received MSDP packets."
  cisco.ios.ios_config:
    lines:
      - "ip msdp password peer {{ peer_address }} {{ secret_key }}"
  notify: Save running configuration
  tags:
    - CISC-RT-000910
    - cat2
    - authentication

