---
# =========================================
# Cisco IOS Router RTR STIG - Encryption
# 2 rules
# =========================================

# -----------------------------------------
# CISC-RT-000400 - MEDIUM
# -----------------------------------------

- name: "CISC-RT-000400 | The Cisco out-of-band management (OOBM) gateway router must be configured to transport management traffic to the Network Operations Center (NOC) via dedicated circuit, MPLS/VPN service, or IPsec tu..."
  cisco.ios.ios_acls:
    config: "{{ cisco_ios_router_rtr_stig_acl_config | default([]) }}"
    state: merged
  notify: Save running configuration
  tags:
    - CISC-RT-000400
    - cat2
    - encryption

# -----------------------------------------
# CISC-RT-000460 - MEDIUM
# -----------------------------------------

- name: "CISC-RT-000460 | The Cisco router providing connectivity to the Network Operations Center (NOC) must be configured to forward all in-band management traffic via an IPsec tunnel."
  cisco.ios.ios_acls:
    config: "{{ cisco_ios_router_rtr_stig_acl_config | default([]) }}"
    state: merged
  notify: Save running configuration
  tags:
    - CISC-RT-000460
    - cat2
    - encryption

