---
galaxy_info:
  role_name: f5_nginx_stig
  author: Fourth Estate
  description: >-
    F5 NGINX Web Server DISA STIG V1 hardening role.
    Implements 32 XCCDF rules across access control, authentication, authorization, encryption, logging, network services, session management.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Generic
      versions:
        - all
  galaxy_tags:
    - f5_bigip
    - stig
    - disa
    - hardening
    - security
    - compliance

dependencies: []

