---
# =========================================
# Cisco IOS-XE Switch L2S STIG - Network Services
# 3 rules
# =========================================

# -----------------------------------------
# CISC-L2-000040 - MEDIUM
# -----------------------------------------

- name: "CISC-L2-000040 | The Cisco switch must manage excess bandwidth to limit the effects of packet flooding types of denial-of-service (DoS) attacks."
  cisco.ios.ios_config:
    lines:
      - "class-map match-all C2_VOICE"
      - "match ip dscp 47"
      - "class-map match-all VOICE"
      - "match ip dscp ef"
      - "class-map match-all VIDEO"
  notify: Save running configuration
  tags:
    - CISC-L2-000040
    - cat2
    - network_services

# -----------------------------------------
# CISC-L2-000130 - MEDIUM
# -----------------------------------------

- name: "CISC-L2-000130 | The Cisco switch must have DHCP snooping for all user VLANs to validate DHCP messages from untrusted sources."
  cisco.ios.ios_config:
    lines:
      - "ip dhcp snooping"
      - "ip dhcp snooping vlan 2,4-8,11"
  notify: Save running configuration
  tags:
    - CISC-L2-000130
    - cat2
    - network_services

# -----------------------------------------
# CISC-L2-000170 - LOW
# -----------------------------------------

- name: "CISC-L2-000170 | The Cisco switch must have IGMP or MLD Snooping configured on all VLANs."
  cisco.ios.ios_config:
    lines:
      - "ip igmp snooping"
  notify: Save running configuration
  tags:
    - CISC-L2-000170
    - cat3
    - network_services

