---
argument_specs:
  main:
    short_description: Cisco IOS Switch RTR DISA STIG V3 hardening
    description:
      - Applies Cisco IOS Switch RTR STIG hardening configuration.
    options:
      cisco_ios_switch_rtr_stig_auto_save:
        type: bool
        default: true
        description: Automatically save configuration after changes.

