---
galaxy_info:
  role_name: cisco_ios_switch_rtr_stig
  author: Fourth Estate
  description: >-
    Cisco IOS Switch RTR DISA STIG V3 hardening role.
    Implements 53 XCCDF rules across access control, authentication, authorization, logging, network services, routing, system hardening.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Generic
      versions:
        - all
  galaxy_tags:
    - cisco
    - stig
    - disa
    - hardening
    - security
    - compliance

dependencies: []

