---
# =========================================
# Cisco NX-OS Switch NDM DISA STIG V3 - Internal Variables
# These are STIG-mandated constants that should
# not normally be overridden.
# =========================================

cisco_nxos_switch_ndm_stig_stig_version: "3"
cisco_nxos_switch_ndm_stig_stig_release_info: "Release: 6 Benchmark Date: 05 Jan 2026"
cisco_nxos_switch_ndm_stig_stig_benchmark_id: "Cisco_NX-OS_Switch_NDM_STIG"
cisco_nxos_switch_ndm_stig_stig_total_rules: 42

