---
# =========================================
# Cisco IOS-XE Router RTR STIG - Logging
# 1 rules
# =========================================

# -----------------------------------------
# CISC-RT-000890 - MEDIUM
# -----------------------------------------

- name: "CISC-RT-000890 | The Cisco multicast Designated Router (DR) must be configured to set the shortest-path tree (SPT) threshold to infinity to minimalize source-group (S, G) state within the multicast topology where A..."
  cisco.ios.ios_config:
    lines:
      - "ip pim spt-threshold infinity"
  notify: Save running configuration
  tags:
    - CISC-RT-000890
    - cat2
    - logging

