---
# =========================================
# Cisco ACI NDM STIG - Session Management
# 1 rules
# =========================================

# -----------------------------------------
# CACI-ND-000054 - HIGH
# -----------------------------------------

- name: "CACI-ND-000054 | Cisco ACI SSH sessions must be terminated after five minutes of inactivity."
  cisco.aci.aci_rest:
    path: "{{ cisco_aci_ndm_stig_caci_nd_000054_api_path | default('/api/mo/uni.json') }}"
    method: post
    content: "{{ cisco_aci_ndm_stig_caci_nd_000054_content | default({}) }}"
  notify: Commit ACI configuration
  tags:
    - CACI-ND-000054
    - cat1
    - session_management

