---
# =========================================
# Cisco ASA IPS STIG - System Hardening
# 1 rules
# =========================================

# -----------------------------------------
# CASA-IP-000270 - MEDIUM
# -----------------------------------------

- name: "CASA-IP-000270 | MANUAL CHECK - The Cisco ASA must be configured to block traffic from IP addresses that have a known bad reputation based on the latest reputation intelligence."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure the ASA as required."
  tags:
    - CASA-IP-000270
    - cat2
    - system_hardening

