---
# =========================================
# Cisco IOS-XR Router NDM STIG - Logging
# 8 rules
# =========================================

# -----------------------------------------
# CISC-ND-000250 - MEDIUM
# -----------------------------------------

- name: "CISC-ND-000250 | MANUAL CHECK - The Cisco router must be configured to generate audit records when successful/unsuccessful attempts to logon with access privileges occur."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure the device CLI as required."
  tags:
    - CISC-ND-000250
    - cat2
    - logging

# -----------------------------------------
# CISC-ND-000280 - MEDIUM
# -----------------------------------------

- name: "CISC-ND-000280 | MANUAL CHECK - The Cisco router must produce audit records containing information to establish when (date and time) the events occurred."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure the device CLI as required."
  tags:
    - CISC-ND-000280
    - cat2
    - logging

# -----------------------------------------
# CISC-ND-000980 - MEDIUM
# -----------------------------------------

- name: "CISC-ND-000980 | MANUAL CHECK - The Cisco router must be configured to allocate audit record storage capacity in accordance with organization-defined audit record storage requirement"
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure the device CLI as required."
  tags:
    - CISC-ND-000980
    - cat2
    - logging

# -----------------------------------------
# CISC-ND-001000 - MEDIUM
# -----------------------------------------

- name: "CISC-ND-001000 | MANUAL CHECK - The Cisco router must be configured to generate an alert for all audit failure events."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure the device CLI as required."
  tags:
    - CISC-ND-001000
    - cat2
    - logging

# -----------------------------------------
# CISC-ND-001040 - MEDIUM
# -----------------------------------------

- name: "CISC-ND-001040 | MANUAL CHECK - The Cisco router must record time stamps for audit records that meet a granularity of one second for a minimum degree of precision."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure the device CLI as required."
  tags:
    - CISC-ND-001040
    - cat2
    - logging

# -----------------------------------------
# CISC-ND-001050 - MEDIUM
# -----------------------------------------

- name: "CISC-ND-001050 | MANUAL CHECK - The Cisco router must be configured to record time stamps for log records that can be mapped to Coordinated Universal Time (UTC) or Greenwich Mean Tim"
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure the device CLI as required."
  tags:
    - CISC-ND-001050
    - cat2
    - logging

# -----------------------------------------
# CISC-ND-001310 - MEDIUM
# -----------------------------------------

- name: "CISC-ND-001310 | MANUAL CHECK - The Cisco router must be configured to off-load log records onto a different system than the system being audited."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure the device CLI as required."
  tags:
    - CISC-ND-001310
    - cat2
    - logging

# -----------------------------------------
# CISC-ND-001450 - HIGH
# -----------------------------------------

- name: "CISC-ND-001450 | MANUAL CHECK - The Cisco router must be configured to send log data to at least two syslog servers for the purpose of forwarding alerts to the administrators and the"
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Review STIG fixtext and configure the device CLI as required."
  tags:
    - CISC-ND-001450
    - cat1
    - logging

