---
galaxy_info:
  role_name: cisco_aci_ndm_stig
  author: Fourth Estate
  description: >-
    Cisco ACI NDM DISA STIG V1 hardening role.
    Implements 26 XCCDF rules across authentication, authorization, encryption, logging, network services, session management, system hardening.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Generic
      versions:
        - all
  galaxy_tags:
    - cisco
    - stig
    - disa
    - hardening
    - security
    - compliance

dependencies: []

