---
# =========================================
# Cisco NX-OS Switch L2S DISA STIG V3 - Internal Variables
# These are STIG-mandated constants that should
# not normally be overridden.
# =========================================

cisco_nxos_switch_l2s_stig_stig_version: "3"
cisco_nxos_switch_l2s_stig_stig_release_info: "Release: 3 Benchmark Date: 05 Jan 2026"
cisco_nxos_switch_l2s_stig_stig_benchmark_id: "Cisco_NX-OS_Switch_L2S_STIG"
cisco_nxos_switch_l2s_stig_stig_total_rules: 22

