---
argument_specs:
  main:
    short_description: Cisco ASA NDM DISA STIG V2 hardening
    description:
      - Applies Cisco ASA NDM STIG hardening configuration.
    options:
      cisco_asa_ndm_stig_auto_save:
        type: bool
        default: true
        description: Automatically save configuration after changes.

