---
galaxy_info:
  role_name: cisco_iosxe_switch_l2s_stig
  author: Fourth Estate
  description: >-
    Cisco IOS-XE Switch L2S DISA STIG V3 hardening role.
    Implements 22 XCCDF rules across authentication, network services, switching, system hardening.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Generic
      versions:
        - all
  galaxy_tags:
    - cisco
    - stig
    - disa
    - hardening
    - security
    - compliance

dependencies: []

