---
galaxy_info:
  role_name: mssql_2022_database_stig
  author: Fourth Estate
  description: >-
    MS SQL Server 2022 Database DISA STIG V1 hardening role.
    Implements 22 XCCDF rules across authentication, authorization, backup recovery, logging, network services, system hardening.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Generic
      versions:
        - all
  galaxy_tags:
    - mssql
    - stig
    - disa
    - hardening
    - security
    - compliance

dependencies: []

