---
# =========================================
# Cisco ASA VPN DISA STIG V2 - Internal Variables
# These are STIG-mandated constants that should
# not normally be overridden.
# =========================================

cisco_asa_vpn_stig_stig_version: "2"
cisco_asa_vpn_stig_stig_release_info: "Release: 2 Benchmark Date: 24 Oct 2024"
cisco_asa_vpn_stig_stig_benchmark_id: "Cisco_ASA_VPN_STIG"
cisco_asa_vpn_stig_stig_total_rules: 41

