---
argument_specs:
  main:
    short_description: Palo Alto Prisma Cloud Compute Cloud DISA STIG V2 hardening
    description:
      - Applies Palo Alto Prisma Cloud Compute Cloud STIG hardening configuration.
    options:
      pan_prisma_cloud_stig_auto_commit:
        type: bool
        default: false
        description: Automatically commit configuration after changes.

