---
# =========================================
# Cisco ACI RTR STIG - Logging
# 2 rules
# =========================================

# -----------------------------------------
# CACI-RT-000026 - MEDIUM
# -----------------------------------------

- name: "CACI-RT-000026 | MANUAL CHECK - The Cisco ACI must be configured to have gratuitous ARP (GARP) disabled on all external interfaces."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Disable GARP for each L3OUT Bridge Domain: 1. In the APIC GUI navigation pane, select \"Tenant\" and complete the following for each tenant listed. 2. Expand \"Networking\", right-click, \"Create B..."
  tags:
    - CACI-RT-000026
    - cat2
    - logging

# -----------------------------------------
# CACI-RT-000043 - MEDIUM
# -----------------------------------------

- name: "CACI-RT-000043 | MANUAL CHECK - The Cisco ACI must establish organization-defined alternate communication paths for system operations organizational command and control."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Configure logical separation using EPGs, bridge domains, and/or tenants in accordance with the SSP. There are a large number of spots to validate that each EPG is using an organizational defined VL..."
  tags:
    - CACI-RT-000043
    - cat2
    - logging

