---
# =========================================
# Cisco IOS-XR Router NDM DISA STIG V3 - Internal Variables
# These are STIG-mandated constants that should
# not normally be overridden.
# =========================================

cisco_iosxr_router_ndm_stig_stig_version: "3"
cisco_iosxr_router_ndm_stig_stig_release_info: "Release: 5 Benchmark Date: 05 Jan 2026"
cisco_iosxr_router_ndm_stig_stig_benchmark_id: "Cisco_IOS-XR_Router_NDM_STIG"
cisco_iosxr_router_ndm_stig_stig_total_rules: 27

