---
argument_specs:
  main:
    short_description: F5 BIG-IP NDM DISA STIG V1 hardening
    description:
      - Applies F5 BIG-IP NDM STIG hardening configuration.
    options:
      f5_bigip_ndm_stig_auto_save:
        type: bool
        default: true
        description: Automatically save configuration after changes.

