---
# =========================================
# MS SQL Server 2022 Database STIG - Backup Recovery
# 1 rules
# =========================================

# -----------------------------------------
# SQLD-22-001500 - MEDIUM
# -----------------------------------------

- name: "SQLD-22-001500 | MANUAL CHECK - In the event of a system failure, hardware loss or disk failure, SQL Server must be able to restore necessary databases with least disruption to mission processes."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Modify the system security plan to include whether the database is static, the correct recovery model to be used, the backup schedule, and the plan for testing database restoration. In SQL Server M..."
  tags:
    - SQLD-22-001500
    - cat2
    - backup_recovery

