---
# =========================================
# MS SQL Server 2016 Database STIG - Logging
# 1 rules
# =========================================

# -----------------------------------------
# SQL6-D0-001700 - MEDIUM
# -----------------------------------------

- name: "SQL6-D0-001700 | The Database Master Key must be encrypted by the Service Master Key, where a Database Master Key is required and another encryption method has not been specified."
  community.general.mssql_script:
    login_user: "{{ mssql_2016_database_stig_db_user }}"
    login_password: "{{ mssql_2016_database_stig_db_password }}"
    login_host: "{{ mssql_2016_database_stig_db_host }}"
    script: |
      SELECT 1 -- TODO: Review STIG fixtext and implement appropriate SQL
  notify: Restart SQL Server service
  tags:
    - SQL6-D0-001700
    - cat2
    - logging

