---
# =========================================
# MS SQL Server 2016 Database STIG - Network Services
# 4 rules
# =========================================

# -----------------------------------------
# SQL6-D0-000500 - LOW
# -----------------------------------------

- name: "SQL6-D0-000500 | SQL Server must protect against a user falsely repudiating by use of system-versioned tables (Temporal Tables)."
  community.general.mssql_script:
    login_user: "{{ mssql_2016_database_stig_db_user }}"
    login_password: "{{ mssql_2016_database_stig_db_password }}"
    login_host: "{{ mssql_2016_database_stig_db_host }}"
    script: |
      ALTER TABLE {{ mssql_2016_database_stig_temporal_table_name }}
      ADD PERIOD FOR SYSTEM_TIME (SysStartTime, SysEndTime);
      ALTER TABLE {{ mssql_2016_database_stig_temporal_table_name }}
      SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.{{ mssql_2016_database_stig_temporal_table_name }}_History));
  notify: Restart SQL Server service
  tags:
    - SQL6-D0-000500
    - cat3
    - network_services

# -----------------------------------------
# SQL6-D0-002600 - MEDIUM
# -----------------------------------------

- name: "SQL6-D0-002600 | SQL Server must associate organization-defined types of security labels having organization-defined security label values with information in process, transit, or storage."
  community.general.mssql_script:
    login_user: "{{ mssql_2016_database_stig_db_user }}"
    login_password: "{{ mssql_2016_database_stig_db_password }}"
    login_host: "{{ mssql_2016_database_stig_db_host }}"
    script: |
      SELECT 1 -- TODO: Review STIG fixtext and implement appropriate SQL
  notify: Restart SQL Server service
  tags:
    - SQL6-D0-002600
    - cat2
    - network_services

# -----------------------------------------
# SQL6-D0-003100 - MEDIUM
# -----------------------------------------

- name: "SQL6-D0-003100 | SQL Server must enforce access restrictions associated with changes to the configuration of the database(s)."
  community.general.mssql_script:
    login_user: "{{ mssql_2016_database_stig_db_user }}"
    login_password: "{{ mssql_2016_database_stig_db_password }}"
    login_host: "{{ mssql_2016_database_stig_db_host }}"
    script: |
      ALTER ROLE {{ mssql_2016_database_stig_role_name }} DROP MEMBER {{ mssql_2016_database_stig_member_name }};
  notify: Restart SQL Server service
  tags:
    - SQL6-D0-003100
    - cat2
    - network_services

# -----------------------------------------
# SQL6-D0-003300 - HIGH
# -----------------------------------------

- name: "SQL6-D0-003300 | MANUAL CHECK - SQL Server must implement cryptographic mechanisms to prevent unauthorized modification of organization-defined information at rest (to include, at a minimum, PII and classified information) on org..."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Where full-disk encryption is required, configure Windows and/or the storage system to provide this. Where transparent data encryption (TDE) is required, create a master key, obtain a certificate p..."
  tags:
    - SQL6-D0-003300
    - cat1
    - network_services

