---
# =========================================
# MS SQL Server 2022 Instance STIG - Encryption
# 4 rules
# =========================================

# -----------------------------------------
# SQLI-22-008300 - HIGH
# -----------------------------------------

- name: "SQLI-22-008300 | MANUAL CHECK - Confidentiality of information during transmission must be controlled through the use of an approved TLS version."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Important Note: Incorrectly modifying the Windows Registry can result in serious system errors. Before making any modifications, ensure there is a recent backup of the system and registry settings...."
  tags:
    - SQLI-22-008300
    - cat1
    - encryption

# -----------------------------------------
# SQLI-22-008700 - HIGH
# -----------------------------------------

- name: "SQLI-22-008700 | SQL Server must use NIST FIPS 140-2 or 140-3 validated cryptographic operations for encryption, hashing, and signing."
  community.general.mssql_script:
    login_user: "{{ mssql_2022_instance_stig_db_user }}"
    login_password: "{{ mssql_2022_instance_stig_db_password }}"
    login_host: "{{ mssql_2022_instance_stig_db_host }}"
    script: |
      SELECT 1 -- TODO: Review STIG fixtext and implement appropriate SQL
  notify: Restart SQL Server service
  tags:
    - SQLI-22-008700
    - cat1
    - encryption

# -----------------------------------------
# SQLI-22-016500 - MEDIUM
# -----------------------------------------

- name: "SQLI-22-016500 | The SQL Server Mirroring endpoint must use AES encryption."
  community.general.mssql_script:
    login_user: "{{ mssql_2022_instance_stig_db_user }}"
    login_password: "{{ mssql_2022_instance_stig_db_password }}"
    login_host: "{{ mssql_2022_instance_stig_db_host }}"
    script: |
      ALTER ENDPOINT {{ endpoint_name }}
  notify: Restart SQL Server service
  tags:
    - SQLI-22-016500
    - cat2
    - encryption

# -----------------------------------------
# SQLI-22-016600 - MEDIUM
# -----------------------------------------

- name: "SQLI-22-016600 | The SQL Server Service Broker endpoint must use AES encryption."
  community.general.mssql_script:
    login_user: "{{ mssql_2022_instance_stig_db_user }}"
    login_password: "{{ mssql_2022_instance_stig_db_password }}"
    login_host: "{{ mssql_2022_instance_stig_db_host }}"
    script: |
      ALTER ENDPOINT {{ endpointname }}
  notify: Restart SQL Server service
  tags:
    - SQLI-22-016600
    - cat2
    - encryption

