---
# =========================================
# MS SQL Server 2022 Instance STIG - Logging
# 13 rules
# =========================================

# -----------------------------------------
# SQLI-22-004000 - MEDIUM
# -----------------------------------------

- name: "SQLI-22-004000 | SQL Server must protect against a user falsely repudiating by ensuring all accounts are individual, unique, and not shared."
  community.general.mssql_script:
    login_user: "{{ mssql_2022_instance_stig_db_user }}"
    login_password: "{{ mssql_2022_instance_stig_db_password }}"
    login_host: "{{ mssql_2022_instance_stig_db_host }}"
    script: |
      SELECT 1 -- TODO: Review STIG fixtext and implement appropriate SQL
  notify: Restart SQL Server service
  tags:
    - SQLI-22-004000
    - cat2
    - logging

# -----------------------------------------
# SQLI-22-004300 - MEDIUM
# -----------------------------------------

- name: "SQLI-22-004300 | SQL Server must be configured to generate audit records for DOD-defined auditable events within all DBMS/database components."
  community.general.mssql_script:
    login_user: "{{ mssql_2022_instance_stig_db_user }}"
    login_password: "{{ mssql_2022_instance_stig_db_password }}"
    login_host: "{{ mssql_2022_instance_stig_db_host }}"
    script: |
      SELECT 1 -- TODO: Review STIG fixtext and implement appropriate SQL
  notify: Restart SQL Server service
  tags:
    - SQLI-22-004300
    - cat2
    - logging

# -----------------------------------------
# SQLI-22-004600 - MEDIUM
# -----------------------------------------

- name: "SQLI-22-004600 | SQL Server must generate audit records when attempts to access privileges, categorized information, and security objects occur."
  community.general.mssql_script:
    login_user: "{{ mssql_2022_instance_stig_db_user }}"
    login_password: "{{ mssql_2022_instance_stig_db_password }}"
    login_host: "{{ mssql_2022_instance_stig_db_host }}"
    script: |
      SELECT 1 -- TODO: Review STIG fixtext and implement appropriate SQL
  notify: Restart SQL Server service
  tags:
    - SQLI-22-004600
    - cat2
    - logging

# -----------------------------------------
# SQLI-22-004700 - MEDIUM
# -----------------------------------------

- name: "SQLI-22-004700 | SQL Server must initiate session auditing upon startup."
  community.general.mssql_script:
    login_user: "{{ mssql_2022_instance_stig_db_user }}"
    login_password: "{{ mssql_2022_instance_stig_db_password }}"
    login_host: "{{ mssql_2022_instance_stig_db_host }}"
    script: |
      ALTER SERVER AUDIT [{{ server_audit_name }}] WITH STATE = ON
  notify: Restart SQL Server service
  tags:
    - SQLI-22-004700
    - cat2
    - logging

# -----------------------------------------
# SQLI-22-005500 - MEDIUM
# -----------------------------------------

- name: "SQLI-22-005500 | SQL Server must include additional, more detailed, organization-defined information in the audit records for audit events identified by type, location, or subject."
  community.general.mssql_script:
    login_user: "{{ mssql_2022_instance_stig_db_user }}"
    login_password: "{{ mssql_2022_instance_stig_db_password }}"
    login_host: "{{ mssql_2022_instance_stig_db_host }}"
    script: |
      SELECT 1 -- TODO: Review STIG fixtext and implement appropriate SQL
  notify: Restart SQL Server service
  tags:
    - SQLI-22-005500
    - cat2
    - logging

# -----------------------------------------
# SQLI-22-017600 - MEDIUM
# -----------------------------------------

- name: "SQLI-22-017600 | The remote Data Archive feature must be disabled unless specifically required and approved."
  community.general.mssql_script:
    login_user: "{{ mssql_2022_instance_stig_db_user }}"
    login_password: "{{ mssql_2022_instance_stig_db_password }}"
    login_host: "{{ mssql_2022_instance_stig_db_host }}"
    script: |
      EXEC SP_CONFIGURE 'Remote Data Archive', 0;
  notify: Restart SQL Server service
  tags:
    - SQLI-22-017600
    - cat2
    - logging

# -----------------------------------------
# SQLI-22-010900 - MEDIUM
# -----------------------------------------

- name: "SQLI-22-010900 | SQL Server must allocate audit record storage capacity in accordance with organization-defined audit record storage requirements."
  community.general.mssql_script:
    login_user: "{{ mssql_2022_instance_stig_db_user }}"
    login_password: "{{ mssql_2022_instance_stig_db_password }}"
    login_host: "{{ mssql_2022_instance_stig_db_host }}"
    script: |
      SELECT 1 -- TODO: Review STIG fixtext and implement appropriate SQL
  notify: Restart SQL Server service
  tags:
    - SQLI-22-010900
    - cat2
    - logging

# -----------------------------------------
# SQLI-22-011000 - MEDIUM
# -----------------------------------------

- name: "SQLI-22-011000 | SQL Server must provide a warning to appropriate support staff when allocated audit record storage volume reaches 75 percent of maximum audit record storage capacity."
  community.general.mssql_script:
    login_user: "{{ mssql_2022_instance_stig_db_user }}"
    login_password: "{{ mssql_2022_instance_stig_db_password }}"
    login_host: "{{ mssql_2022_instance_stig_db_host }}"
    script: |
      SELECT 1 -- TODO: Review STIG fixtext and implement appropriate SQL
  notify: Restart SQL Server service
  tags:
    - SQLI-22-011000
    - cat2
    - logging

# -----------------------------------------
# SQLI-22-011100 - MEDIUM
# -----------------------------------------

- name: "SQLI-22-011100 | SQL Server must provide an immediate real-time alert to appropriate support staff of all audit log failures."
  community.general.mssql_script:
    login_user: "{{ mssql_2022_instance_stig_db_user }}"
    login_password: "{{ mssql_2022_instance_stig_db_password }}"
    login_host: "{{ mssql_2022_instance_stig_db_host }}"
    script: |
      SELECT 1 -- TODO: Review STIG fixtext and implement appropriate SQL
  notify: Restart SQL Server service
  tags:
    - SQLI-22-011100
    - cat2
    - logging

# -----------------------------------------
# SQLI-22-011200 - MEDIUM
# -----------------------------------------

- name: "SQLI-22-011200 | MANUAL CHECK - SQL Server must record time stamps in audit records and application data that can be mapped to Coordinated Universal Time (UTC), formerly Greenwich Mean Time (GMT)."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Where possible, configure the operating system to automatic synchronize with an official time server, using NTP. Where there is reason not to implement automatic synchronization with an official ti..."
  tags:
    - SQLI-22-011200
    - cat2
    - logging

# -----------------------------------------
# SQLI-22-012400 - MEDIUM
# -----------------------------------------

- name: "SQLI-22-012400 | MANUAL CHECK - SQL Server services must be configured to run under unique dedicated user accounts."
  ansible.builtin.debug:
    msg: "MANUAL CHECK: Configure SQL Server services to have a documented, dedicated account. For nondomain servers, consider using virtual service accounts (VSAs). For more information, refer to: https://learn.microsoft..."
  tags:
    - SQLI-22-012400
    - cat2
    - logging

# -----------------------------------------
# SQLI-22-015500 - MEDIUM
# -----------------------------------------

- name: "SQLI-22-015500 | SQL Server must generate audit records for all direct access to the database(s)."
  community.general.mssql_script:
    login_user: "{{ mssql_2022_instance_stig_db_user }}"
    login_password: "{{ mssql_2022_instance_stig_db_password }}"
    login_host: "{{ mssql_2022_instance_stig_db_host }}"
    script: |
      SELECT 1 -- TODO: Review STIG fixtext and implement appropriate SQL
  notify: Restart SQL Server service
  tags:
    - SQLI-22-015500
    - cat2
    - logging

# -----------------------------------------
# SQLI-22-015900 - MEDIUM
# -----------------------------------------

- name: "SQLI-22-015900 | The system SQL Server must off-load audit data to a separate log management facility; this must be continuous and in near real time for systems with a network connection to the storage facility and..."
  community.general.mssql_script:
    login_user: "{{ mssql_2022_instance_stig_db_user }}"
    login_password: "{{ mssql_2022_instance_stig_db_password }}"
    login_host: "{{ mssql_2022_instance_stig_db_host }}"
    script: |
      SELECT 1 -- TODO: Review STIG fixtext and implement appropriate SQL
  notify: Restart SQL Server service
  tags:
    - SQLI-22-015900
    - cat2
    - logging

