---
# =========================================
# MS SQL Server 2022 Instance STIG - Network Services
# 6 rules
# =========================================

# -----------------------------------------
# SQLI-22-003800 - HIGH
# -----------------------------------------

- name: "SQLI-22-003800 | SQL Server must be configured to use the most-secure authentication method available."
  community.general.mssql_script:
    login_user: "{{ mssql_2022_instance_stig_db_user }}"
    login_password: "{{ mssql_2022_instance_stig_db_password }}"
    login_host: "{{ mssql_2022_instance_stig_db_host }}"
    script: |
      SELECT 1 -- TODO: Review STIG fixtext and implement appropriate SQL
  notify: Restart SQL Server service
  tags:
    - SQLI-22-003800
    - cat1
    - network_services

# -----------------------------------------
# SQLI-22-006600 - MEDIUM
# -----------------------------------------

- name: "SQLI-22-006600 | SQL Server must limit privileges to change software modules, to include stored procedures, functions and triggers, and links to software external to SQL Server."
  community.general.mssql_script:
    login_user: "{{ mssql_2022_instance_stig_db_user }}"
    login_password: "{{ mssql_2022_instance_stig_db_password }}"
    login_host: "{{ mssql_2022_instance_stig_db_host }}"
    script: |
      SELECT 1 -- TODO: Review STIG fixtext and implement appropriate SQL
  notify: Restart SQL Server service
  tags:
    - SQLI-22-006600
    - cat2
    - network_services

# -----------------------------------------
# SQLI-22-008000 - HIGH
# -----------------------------------------

- name: "SQLI-22-008000 | Contained databases must use Windows principals."
  community.general.mssql_script:
    login_user: "{{ mssql_2022_instance_stig_db_user }}"
    login_password: "{{ mssql_2022_instance_stig_db_password }}"
    login_host: "{{ mssql_2022_instance_stig_db_host }}"
    script: |
      SELECT 1 -- TODO: Review STIG fixtext and implement appropriate SQL
  notify: Restart SQL Server service
  tags:
    - SQLI-22-008000
    - cat1
    - network_services

# -----------------------------------------
# SQLI-22-011800 - MEDIUM
# -----------------------------------------

- name: "SQLI-22-011800 | SQL Server must produce audit records when attempts to modify SQL Server configuration and privileges occur within the database(s)."
  community.general.mssql_script:
    login_user: "{{ mssql_2022_instance_stig_db_user }}"
    login_password: "{{ mssql_2022_instance_stig_db_password }}"
    login_host: "{{ mssql_2022_instance_stig_db_host }}"
    script: |
      SELECT 1 -- TODO: Review STIG fixtext and implement appropriate SQL
  notify: Restart SQL Server service
  tags:
    - SQLI-22-011800
    - cat2
    - network_services

# -----------------------------------------
# SQLI-22-013800 - MEDIUM
# -----------------------------------------

- name: "SQLI-22-013800 | SQL Server must generate audit records when successful and unsuccessful attempts to modify or delete security objects occur."
  community.general.mssql_script:
    login_user: "{{ mssql_2022_instance_stig_db_user }}"
    login_password: "{{ mssql_2022_instance_stig_db_password }}"
    login_host: "{{ mssql_2022_instance_stig_db_host }}"
    script: |
      SELECT 1 -- TODO: Review STIG fixtext and implement appropriate SQL
  notify: Restart SQL Server service
  tags:
    - SQLI-22-013800
    - cat2
    - network_services

# -----------------------------------------
# SQLI-22-016100 - MEDIUM
# -----------------------------------------

- name: "SQLI-22-016100 | SQL Server must configure SQL Server Usage and Error Reporting Auditing."
  community.general.mssql_script:
    login_user: "{{ mssql_2022_instance_stig_db_user }}"
    login_password: "{{ mssql_2022_instance_stig_db_password }}"
    login_host: "{{ mssql_2022_instance_stig_db_host }}"
    script: |
      SELECT 1 -- TODO: Review STIG fixtext and implement appropriate SQL
  notify: Restart SQL Server service
  tags:
    - SQLI-22-016100
    - cat2
    - network_services

