---
# =========================================
# MS SQL Server 2022 Instance STIG - Routing
# 1 rules
# =========================================

# -----------------------------------------
# SQLI-22-017700 - MEDIUM
# -----------------------------------------

- name: "SQLI-22-017700 | The SQL Server External Scripts Enabled feature must be disabled, unless specifically required and approved."
  community.general.mssql_script:
    login_user: "{{ mssql_2022_instance_stig_db_user }}"
    login_password: "{{ mssql_2022_instance_stig_db_password }}"
    login_host: "{{ mssql_2022_instance_stig_db_host }}"
    script: |
      EXEC SP_CONFIGURE 'External Scripts Enabled', 0;
  notify: Restart SQL Server service
  tags:
    - SQLI-22-017700
    - cat2
    - routing

